<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class BookSeeder extends Seeder
{
    public function run(): void
    {
        // Limpiar libros existentes para evitar duplicados
        DB::table('book_author')->delete();
        DB::table('book_genre')->delete();
        DB::table('books')->delete();

        $books  = $this->getBooks();
        $inserted = 0;

        foreach ($books as $book) {
            $slug = Str::slug($book['title']) . '-' . Str::random(5);

            // ── Insertar libro con columnas EXACTAS de tu BD ──────────────
            $bookId = DB::table('books')->insertGetId([
                'title'                => $book['title'],
                'slug'                 => $slug,
                'description'          => $book['description'],
                'cover_image'          => null,
                'price_cents'          => $book['price_cents'],
                'original_price_cents' => $book['original_price_cents'] ?? null,
                'is_on_sale'           => $book['is_on_sale']       ?? false,
                'discount_percent'     => $book['discount_percent']  ?? 0,
                'has_pdf'              => $book['has_pdf']           ?? true,
                'has_epub'             => $book['has_epub']          ?? true,
                'has_physical'         => $book['has_physical']      ?? false,
                'stock'                => rand(5, 80),
                'rating_avg'           => round(mt_rand(35, 50) / 10, 2),
                'rating_count'         => rand(10, 500),
                'pages'                => $book['pages']             ?? rand(150, 700),
                'language'             => $book['language']          ?? 'es',
                'publisher'            => $book['publisher']         ?? null,
                'published_at'         => now()->subYears(rand(1, 40)),
                'is_featured'          => $book['is_featured']       ?? false,
                'is_bestseller'        => $book['is_bestseller']     ?? false,
                'is_new_arrival'       => $book['is_new_arrival']    ?? false,
                'created_at'           => now(),
                'updated_at'           => now(),
            ]);

            // ── Autores ───────────────────────────────────────────────────
            foreach (($book['authors'] ?? []) as $authorName) {
                $author = DB::table('authors')->where('name', $authorName)->first();
                if (!$author) {
                    $authorId = DB::table('authors')->insertGetId([
                        'name'       => $authorName,
                        'slug'       => Str::slug($authorName) . '-' . Str::random(4),
                        'created_at' => now(),
                        'updated_at' => now(),
                    ]);
                } else {
                    $authorId = $author->id;
                }

                if (!DB::table('book_author')->where('book_id', $bookId)->where('author_id', $authorId)->exists()) {
                    DB::table('book_author')->insert(['book_id' => $bookId, 'author_id' => $authorId]);
                }
            }

            // ── Géneros ───────────────────────────────────────────────────
            foreach (($book['genres'] ?? []) as $genreName) {
                $genre = DB::table('genres')->where('name', $genreName)->first();
                if (!$genre) {
                    $genreId = DB::table('genres')->insertGetId([
                        'name'       => $genreName,
                        'slug'       => Str::slug($genreName),
                        'created_at' => now(),
                        'updated_at' => now(),
                    ]);
                } else {
                    $genreId = $genre->id;
                }

                if (!DB::table('book_genre')->where('book_id', $bookId)->where('genre_id', $genreId)->exists()) {
                    DB::table('book_genre')->insert(['book_id' => $bookId, 'genre_id' => $genreId]);
                }
            }

            $inserted++;
            if ($inserted % 20 === 0) {
                $this->command->info("  → {$inserted} libros insertados...");
            }
        }

        $this->command->info("✅ {$inserted} libros insertados correctamente.");
    }

    private function getBooks(): array
    {
        return [
            // ═══════════════════════════════════════════════════════════════
            // FICCIÓN LATINOAMERICANA
            // ═══════════════════════════════════════════════════════════════
            ['title'=>'Cien Años de Soledad','authors'=>['Gabriel García Márquez'],'genres'=>['Ficción','Realismo Mágico'],'price_cents'=>1499,'is_featured'=>true,'is_bestseller'=>true,'pages'=>432,'publisher'=>'Sudamericana','description'=>'La historia de la familia Buendía a lo largo de siete generaciones en el pueblo mítico de Macondo. Una obra cumbre del realismo mágico latinoamericano que mezcla lo cotidiano con lo fantástico de manera magistral. Considerada una de las novelas más importantes del siglo XX y ganadora del Premio Nobel de Literatura.'],
            ['title'=>'El amor en los tiempos del cólera','authors'=>['Gabriel García Márquez'],'genres'=>['Ficción','Romance'],'price_cents'=>1299,'is_bestseller'=>true,'pages'=>348,'publisher'=>'Oveja Negra','description'=>'Una historia de amor que trasciende el tiempo entre Fermina Daza y Florentino Ariza. Ambientada en una ciudad del Caribe colombiano, narra la espera de cincuenta y tres años de un amor apasionado. García Márquez explora el amor en todas sus formas y etapas de la vida.'],
            ['title'=>'Crónica de una muerte anunciada','authors'=>['Gabriel García Márquez'],'genres'=>['Ficción','Misterio'],'price_cents'=>999,'pages'=>152,'publisher'=>'Sudamericana','description'=>'Todos en el pueblo sabían que los hermanos Vicario iban a matar a Santiago Nasar, pero nadie lo impidió. García Márquez reconstruye el crimen colectivo con la estructura de un relato policial y la densidad de una tragedia griega.'],
            ['title'=>'El general en su laberinto','authors'=>['Gabriel García Márquez'],'genres'=>['Ficción Histórica'],'price_cents'=>1199,'pages'=>268,'publisher'=>'Oveja Negra','description'=>'Los últimos días de Simón Bolívar en su viaje fluvial hacia Santa Marta. García Márquez reconstruye el ocaso del Libertador con realismo magistral y profunda humanidad, mostrando al hombre detrás del mito histórico.'],
            ['title'=>'La hojarasca','authors'=>['Gabriel García Márquez'],'genres'=>['Ficción'],'price_cents'=>899,'pages'=>128,'publisher'=>'Sudamericana','description'=>'La primera novela de García Márquez, ambientada en Macondo. Tres personajes velan un cadáver y recuerdan su historia con el pueblo. El germen de todo el universo mítico que culminaría en Cien años de soledad.'],
            ['title'=>'El otoño del patriarca','authors'=>['Gabriel García Márquez'],'genres'=>['Ficción'],'price_cents'=>1199,'pages'=>360,'publisher'=>'Plaza & Janés','description'=>'Un anciano dictador caribeño vive aislado en su palacio, rodeado de miedo y adulación. García Márquez crea un retrato del poder absoluto y la soledad del tirano en una prosa torrencial y alucinante.'],
            ['title'=>'Rayuela','authors'=>['Julio Cortázar'],'genres'=>['Ficción','Vanguardia'],'price_cents'=>1399,'is_featured'=>true,'pages'=>635,'publisher'=>'Sudamericana','description'=>'Una novela experimental que puede leerse en múltiples órdenes. Sigue a Horacio Oliveira entre París y Buenos Aires en su búsqueda existencial. Una obra revolucionaria de la literatura hispanoamericana que reinventó la novela.'],
            ['title'=>'Ficciones','authors'=>['Jorge Luis Borges'],'genres'=>['Ficción','Cuento'],'price_cents'=>999,'pages'=>174,'publisher'=>'Emecé','description'=>'Colección de cuentos fantásticos que exploran laberintos, bibliotecas infinitas, espejos y sueños. Borges construye universos paralelos con una precisión matemática y una imaginación desbordante. La obra más influyente de la literatura argentina.'],
            ['title'=>'El Aleph','authors'=>['Jorge Luis Borges'],'genres'=>['Ficción','Cuento'],'price_cents'=>999,'pages'=>204,'publisher'=>'Emecé','description'=>'Una colección de relatos donde lo fantástico se funde con lo filosófico. El cuento central narra el descubrimiento de un punto del espacio que contiene todos los puntos del universo. Borges en su máxima expresión literaria.'],
            ['title'=>'Pedro Páramo','authors'=>['Juan Rulfo'],'genres'=>['Ficción','Realismo Mágico'],'price_cents'=>899,'is_featured'=>true,'pages'=>128,'publisher'=>'FCE','description'=>'Juan Preciado viaja al pueblo fantasma de Comala buscando a su padre, Pedro Páramo. Una novela breve y poderosa que mezcla la voz de los muertos con la historia de un cacique despiadado. Obra fundamental de la literatura mexicana.'],
            ['title'=>'La ciudad y los perros','authors'=>['Mario Vargas Llosa'],'genres'=>['Ficción'],'price_cents'=>1199,'pages'=>408,'publisher'=>'Seix Barral','description'=>'Ambientada en el Colegio Militar Leoncio Prado de Lima, esta novela explora la violencia, la masculinidad y la corrupción moral entre cadetes adolescentes. La primera novela de Vargas Llosa, que lo catapultó a la fama internacional.'],
            ['title'=>'La casa verde','authors'=>['Mario Vargas Llosa'],'genres'=>['Ficción'],'price_cents'=>1199,'pages'=>436,'publisher'=>'Seix Barral','description'=>'Una novela que entrelaza múltiples historias en la selva peruana y en la ciudad de Piura. Explora la explotación, la civilización versus la naturaleza y los contrastes sociales de la sociedad peruana.'],
            ['title'=>'Conversación en La Catedral','authors'=>['Mario Vargas Llosa'],'genres'=>['Ficción'],'price_cents'=>1399,'pages'=>600,'publisher'=>'Seix Barral','description'=>'En un bar de Lima, dos hombres conversan durante cuatro horas sobre el Perú corrupto de la dictadura de Odría. Una novela total sobre el fracaso individual y colectivo, narrada con una técnica narrativa deslumbrante.'],
            ['title'=>'El túnel','authors'=>['Ernesto Sabato'],'genres'=>['Ficción'],'price_cents'=>999,'pages'=>144,'publisher'=>'Sudamericana','description'=>'Un pintor obsesivo narra cómo llegó a asesinar a la única mujer que creyó comprenderlo. Una novela existencialista y psicológica de profunda angustia humana, considerada un clásico de la literatura argentina.'],
            ['title'=>'Delirio','authors'=>['Laura Restrepo'],'genres'=>['Ficción','Literatura Colombiana'],'price_cents'=>1099,'is_featured'=>true,'pages'=>320,'publisher'=>'Alfaguara','description'=>'Premio Alfaguara 2004. Aguilar regresa de un viaje y encuentra a su esposa sumida en la locura. La novela reconstruye lo que ocurrió en el contexto del narcotráfico colombiano de los 90. Una historia de amor y violencia.'],
            ['title'=>'Rosario Tijeras','authors'=>['Jorge Franco'],'genres'=>['Ficción','Literatura Colombiana'],'price_cents'=>999,'pages'=>188,'publisher'=>'Plaza & Janés','description'=>'Rosario Tijeras es una sicaria de las comunas de Medellín. Hermosa y mortal, su vida está marcada por la violencia, el amor imposible y la muerte. Un retrato duro y poético del conflicto urbano colombiano de los 90.'],
            ['title'=>'El mundo de afuera','authors'=>['Jorge Franco'],'genres'=>['Ficción','Literatura Colombiana'],'price_cents'=>1099,'pages'=>298,'publisher'=>'Alfaguara','description'=>'En la Medellín de los años 80, una niña de familia acomodada es secuestrada. La historia entrelaza el mundo de los secuestradores, la familia y la víctima en un retrato íntimo de la violencia colombiana.'],
            ['title'=>'Sin remedio','authors'=>['Antonio Caballero'],'genres'=>['Ficción','Literatura Colombiana'],'price_cents'=>1099,'pages'=>480,'publisher'=>'Alfaguara','description'=>'El poeta bogotano Ignacio Escobar vive su fracaso existencial en la Bogotá de los años 70. Una novela urbana, irónica y despiadada sobre la decadencia de la clase media ilustrada colombiana.'],
            ['title'=>'Los informantes','authors'=>['Juan Gabriel Vásquez'],'genres'=>['Ficción Histórica','Literatura Colombiana'],'price_cents'=>1099,'pages'=>304,'publisher'=>'Alfaguara','description'=>'Colombia durante la Segunda Guerra Mundial persiguió a inmigrantes alemanes acusados de ser espías nazis. Una novela que explora la traición, la memoria y las consecuencias de delatar al otro.'],
            ['title'=>'El ruido de las cosas al caer','authors'=>['Juan Gabriel Vásquez'],'genres'=>['Ficción','Literatura Colombiana'],'price_cents'=>1099,'is_featured'=>true,'pages'=>280,'publisher'=>'Alfaguara','description'=>'Premio Alfaguara 2011. En Bogotá, un hipopótamo de Pablo Escobar escapa del zoológico. Este suceso desencadena una historia sobre el miedo, la violencia del narcotráfico y sus secuelas en una generación colombiana.'],
            ['title'=>'La vorágine','authors'=>['José Eustasio Rivera'],'genres'=>['Ficción','Literatura Colombiana'],'price_cents'=>799,'pages'=>298,'publisher'=>'Cromos','description'=>'Un poeta colombiano huye con su amante a los Llanos Orientales y luego a la selva amazónica. Novela que denuncia la explotación cauchera y retrata la naturaleza como fuerza destructora e implacable.'],

            // ═══════════════════════════════════════════════════════════════
            // CLÁSICOS UNIVERSALES
            // ═══════════════════════════════════════════════════════════════
            ['title'=>'Don Quijote de la Mancha','authors'=>['Miguel de Cervantes'],'genres'=>['Clásico'],'price_cents'=>1799,'is_featured'=>true,'is_bestseller'=>true,'pages'=>1023,'publisher'=>'RAE','description'=>'Un hidalgo manchego enloquece de tanto leer novelas de caballería y decide salir como caballero andante con su fiel escudero Sancho Panza. La obra cumbre de la literatura española y una de las novelas más importantes de la historia universal.'],
            ['title'=>'Crimen y castigo','authors'=>['Fiodor Dostoievski'],'genres'=>['Clásico','Ficción'],'price_cents'=>1199,'is_bestseller'=>true,'pages'=>560,'publisher'=>'Alianza','description'=>'Raskolnikov, un estudiante en San Petersburgo, asesina a una usurera creyendo estar por encima de la moral. Una profunda exploración del crimen, la culpa y la redención. La novela psicológica más influyente de la literatura rusa.'],
            ['title'=>'El idiota','authors'=>['Fiodor Dostoievski'],'genres'=>['Clásico'],'price_cents'=>1299,'pages'=>612,'publisher'=>'Alianza','description'=>'El príncipe Mishkin regresa a Rusia después de un tratamiento por epilepsia. Su bondad absoluta choca con una sociedad corrupta y materialista. Una novela sobre la inocencia y la bondad en un mundo imperfecto.'],
            ['title'=>'Anna Karenina','authors'=>['León Tolstói'],'genres'=>['Clásico','Romance'],'price_cents'=>1399,'is_featured'=>true,'pages'=>864,'publisher'=>'Alianza','description'=>'La aristócrata Anna Karenina abandona a su esposo por el apuesto oficial Vronski. Una novela monumental sobre el amor, la hipocresía social y la búsqueda de sentido en la Rusia zarista del siglo XIX.'],
            ['title'=>'Guerra y paz','authors'=>['León Tolstói'],'genres'=>['Clásico','Ficción Histórica'],'price_cents'=>1899,'pages'=>1392,'publisher'=>'Alianza','description'=>'La épica novela de Tolstói retrata la sociedad rusa durante las guerras napoleónicas. A través de cientos de personajes, explora la historia, el amor, la guerra y el sentido de la existencia humana.'],
            ['title'=>'Madame Bovary','authors'=>['Gustave Flaubert'],'genres'=>['Clásico'],'price_cents'=>999,'pages'=>368,'publisher'=>'Alianza','description'=>'Emma Bovary, esposa de un médico rural, busca escapar del aburrimiento provincial a través de aventuras amorosas y gastos extravagantes. Una crítica devastadora del romanticismo burgués y las ilusiones femeninas del siglo XIX.'],
            ['title'=>'Ulises','authors'=>['James Joyce'],'genres'=>['Clásico','Vanguardia'],'price_cents'=>1599,'pages'=>788,'publisher'=>'Lumen','description'=>'Un día en la vida de Leopold Bloom en Dublín el 16 de junio de 1904. Joyce reinventa el lenguaje narrativo con el monólogo interior y los juegos lingüísticos. La novela modernista más importante de la literatura occidental.'],
            ['title'=>'Moby Dick','authors'=>['Herman Melville'],'genres'=>['Clásico','Aventura'],'price_cents'=>1299,'pages'=>654,'publisher'=>'Alba','description'=>'El capitán Ahab conduce a su barco en una obsesiva cacería de la ballena blanca que le arrancó una pierna. Una novela épica sobre la obsesión, el destino y la naturaleza indomable del universo.'],
            ['title'=>'El gran Gatsby','authors'=>['F. Scott Fitzgerald'],'genres'=>['Clásico'],'price_cents'=>899,'is_bestseller'=>true,'pages'=>208,'publisher'=>'Anagrama','description'=>'Jay Gatsby organiza fiestas suntuosas en los años 20 esperando reencontrarse con Daisy Buchanan. Una novela sobre el sueño americano, la decadencia moral y la futilidad de vivir en el pasado.'],
            ['title'=>'La metamorfosis','authors'=>['Franz Kafka'],'genres'=>['Clásico','Ficción'],'price_cents'=>699,'is_featured'=>true,'pages'=>128,'publisher'=>'Alianza','description'=>'Gregor Samsa despierta convertido en un enorme insecto. Su familia debe adaptarse a la nueva realidad. Una alegoría perfecta sobre la alienación, la burocracia moderna y la pérdida de la humanidad en la sociedad contemporánea.'],
            ['title'=>'El proceso','authors'=>['Franz Kafka'],'genres'=>['Clásico'],'price_cents'=>899,'pages'=>248,'publisher'=>'Alianza','description'=>'Josef K. es arrestado sin saber de qué se le acusa y debe enfrentarse a un sistema judicial absurdo e incomprensible. La visión más perturbadora de Kafka sobre el poder y la impotencia del individuo.'],
            ['title'=>'El viejo y el mar','authors'=>['Ernest Hemingway'],'genres'=>['Clásico'],'price_cents'=>799,'is_bestseller'=>true,'pages'=>128,'publisher'=>'Planeta','description'=>'Santiago, un viejo pescador cubano, lucha solo en alta mar con un enorme marlín. Una novela perfecta sobre la dignidad humana ante el fracaso, la naturaleza indomable y el coraje de perseverar. Premio Pulitzer 1953.'],
            ['title'=>'A quién doblan las campanas','authors'=>['Ernest Hemingway'],'genres'=>['Clásico','Ficción Histórica'],'price_cents'=>1099,'pages'=>489,'publisher'=>'Planeta','description'=>'Durante la Guerra Civil española, el americano Robert Jordan se une a una guerrilla para volar un puente. En tres días de misión se enamora de María. Sobre el valor, el amor y el sacrificio en tiempos de guerra.'],
            ['title'=>'La insoportable levedad del ser','authors'=>['Milan Kundera'],'genres'=>['Ficción','Filosófico'],'price_cents'=>1099,'is_featured'=>true,'pages'=>336,'publisher'=>'Tusquets','description'=>'En la Praga de 1968, el médico Tomás vive entre el amor y la libertad. Una novela filosófica sobre el amor, la historia y la libertad que define la condición humana del siglo XX con elegancia sin igual.'],
            ['title'=>'Los miserables','authors'=>['Victor Hugo'],'genres'=>['Clásico','Ficción Histórica'],'price_cents'=>1799,'is_featured'=>true,'is_bestseller'=>true,'pages'=>1488,'publisher'=>'Alianza','description'=>'Jean Valjean, condenado a trabajos forzados por robar pan, busca redimirse en la Francia del siglo XIX. Una épica sobre la justicia, la compasión y la lucha entre el bien y el mal que sigue conmoviendo al mundo.'],
            ['title'=>'El corazón de las tinieblas','authors'=>['Joseph Conrad'],'genres'=>['Clásico'],'price_cents'=>799,'is_featured'=>true,'pages'=>192,'publisher'=>'Alianza','description'=>'Marlow remonta el río Congo en busca del misterioso Kurtz. Una novela corta sobre la oscuridad del colonialismo y la naturaleza humana que influyó profundamente en toda la literatura del siglo XX.'],

            // ═══════════════════════════════════════════════════════════════
            // CIENCIA FICCIÓN Y DISTOPÍAS
            // ═══════════════════════════════════════════════════════════════
            ['title'=>'1984','authors'=>['George Orwell'],'genres'=>['Ciencia Ficción','Distopía'],'price_cents'=>1099,'is_featured'=>true,'is_bestseller'=>true,'pages'=>336,'publisher'=>'Destino','description'=>'En un estado totalitario del futuro, Winston Smith trabaja reescribiendo la historia. Una aterradora distopía sobre la vigilancia, el control mental y la destrucción de la verdad. Más vigente que nunca en el mundo contemporáneo.'],
            ['title'=>'Un mundo feliz','authors'=>['Aldous Huxley'],'genres'=>['Ciencia Ficción','Distopía'],'price_cents'=>1099,'is_bestseller'=>true,'pages'=>312,'publisher'=>'Debolsillo','description'=>'En el año 2540, la humanidad ha sido condicionada para ser feliz. Una distopía donde la estabilidad se logra sacrificando la libertad, el arte y la familia. Un contrapunto perfecto a 1984 de George Orwell.'],
            ['title'=>'Fahrenheit 451','authors'=>['Ray Bradbury'],'genres'=>['Ciencia Ficción','Distopía'],'price_cents'=>999,'is_featured'=>true,'pages'=>256,'publisher'=>'Minotauro','description'=>'En una sociedad futura donde los libros están prohibidos, el bombero Guy Montag quema libros hasta que un encuentro lo hace cuestionar todo. Una defensa apasionada de la literatura y el pensamiento libre.'],
            ['title'=>'Dune','authors'=>['Frank Herbert'],'genres'=>['Ciencia Ficción'],'price_cents'=>1499,'is_bestseller'=>true,'pages'=>688,'publisher'=>'Debolsillo','description'=>'En el planeta desértico Arrakis, el joven Paul Atreides se convierte en líder de los Fremen. Una épica ciencia ficción con profundas implicaciones ecológicas y políticas. La novela de ciencia ficción más vendida de todos los tiempos.'],
            ['title'=>'Fundación','authors'=>['Isaac Asimov'],'genres'=>['Ciencia Ficción'],'price_cents'=>1199,'is_featured'=>true,'pages'=>296,'publisher'=>'Debolsillo','description'=>'El matemático Hari Seldon desarrolla la psicohistoria y funda una colonia para preservar el conocimiento humano ante la caída del Imperio Galáctico. El inicio de la saga más importante de la ciencia ficción.'],
            ['title'=>'El juego de Ender','authors'=>['Orson Scott Card'],'genres'=>['Ciencia Ficción'],'price_cents'=>1099,'pages'=>352,'publisher'=>'Ediciones B','description'=>'El niño prodigio Ender Wiggin es entrenado para convertirse en el comandante que salvará a la humanidad. Una novela sobre la infancia, la guerra y la culpa con un giro final devastador e inesperado.'],
            ['title'=>'El cuento de la criada','authors'=>['Margaret Atwood'],'genres'=>['Ciencia Ficción','Distopía'],'price_cents'=>1099,'is_featured'=>true,'is_bestseller'=>true,'pages'=>378,'publisher'=>'Salamandra','description'=>'En la República de Gilead, las mujeres fértiles son esclavizadas como criadas. Una distopía feminista de devastadora actualidad que resuena con fuerza en el mundo contemporáneo. Premio Booker Internacional.'],
            ['title'=>'La carretera','authors'=>['Cormac McCarthy'],'genres'=>['Ciencia Ficción','Ficción'],'price_cents'=>1099,'is_bestseller'=>true,'pages'=>304,'publisher'=>'Debolsillo','description'=>'Un padre y su hijo recorren un mundo postapocalíptico devastado. Una novela sobre el amor paternal, la esperanza y lo que significa ser humano cuando la civilización ha desaparecido. Premio Pulitzer 2007.'],
            ['title'=>'Solaris','authors'=>['Stanisław Lem'],'genres'=>['Ciencia Ficción'],'price_cents'=>1099,'pages'=>280,'publisher'=>'Impedimenta','description'=>'Una estación espacial orbita el planeta Solaris, cubierto de un océano viviente que reproduce figuras del inconsciente. Una meditación filosófica sobre los límites del conocimiento humano y la comunicación con lo desconocido.'],
            ['title'=>'Crónicas marcianas','authors'=>['Ray Bradbury'],'genres'=>['Ciencia Ficción'],'price_cents'=>999,'pages'=>240,'publisher'=>'Minotauro','description'=>'Relatos que narran la colonización humana de Marte y el declive de la civilización marciana. Una elegía poética sobre la pérdida, la nostalgia y las consecuencias del imperialismo contada con belleza literaria.'],
            ['title'=>'La naranja mecánica','authors'=>['Anthony Burgess'],'genres'=>['Ciencia Ficción','Distopía'],'price_cents'=>999,'pages'=>256,'publisher'=>'Minotauro','description'=>'Alex, un adolescente violento en una Inglaterra futurista, es sometido a un experimento para eliminar su agresividad. Una novela perturbadora sobre el libre albedrío y el control social que sigue siendo polémica.'],

            // ═══════════════════════════════════════════════════════════════
            // TERROR Y HORROR
            // ═══════════════════════════════════════════════════════════════
            ['title'=>'It','authors'=>['Stephen King'],'genres'=>['Terror'],'price_cents'=>1699,'is_bestseller'=>true,'pages'=>1168,'publisher'=>'Plaza & Janés','description'=>'En el pueblo de Derry, el Club de los Perdedores se enfrenta a una entidad maligna que adopta la forma de sus miedos más profundos, principalmente Pennywise el payaso. La novela de terror más icónica de Stephen King.'],
            ['title'=>'El resplandor','authors'=>['Stephen King'],'genres'=>['Terror'],'price_cents'=>1299,'is_featured'=>true,'is_bestseller'=>true,'pages'=>608,'publisher'=>'Plaza & Janés','description'=>'Jack Torrance lleva a su familia al hotel Overlook durante el invierno. Las fuerzas sobrenaturales del hotel comienzan a corroer su mente. Una novela sobre la locura, el alcoholismo y el horror psicológico más puro.'],
            ['title'=>'Misery','authors'=>['Stephen King'],'genres'=>['Terror','Thriller'],'price_cents'=>1199,'pages'=>368,'publisher'=>'Plaza & Janés','description'=>'El escritor Paul Sheldon es rescatado de un accidente por Annie Wilkes, su fan número uno. Lo que parecía bondad se convierte en una pesadilla de cautiverio y violencia escalofriante.'],
            ['title'=>'Frankenstein','authors'=>['Mary Shelley'],'genres'=>['Terror','Clásico'],'price_cents'=>799,'is_bestseller'=>true,'pages'=>288,'publisher'=>'Alianza','description'=>'El científico Victor Frankenstein crea un ser a partir de partes de cadáveres. Cuando el monstruo cobra vida, lo abandona. Una novela gótica sobre la responsabilidad científica y el rechazo del creador hacia su creación.'],
            ['title'=>'Drácula','authors'=>['Bram Stoker'],'genres'=>['Terror','Clásico'],'price_cents'=>899,'is_bestseller'=>true,'pages'=>416,'publisher'=>'Alianza','description'=>'El conde Drácula viaja de Transilvania a Inglaterra para encontrar nuevas víctimas. Un grupo de valientes, guiados por el profesor Van Helsing, decide enfrentarse al poderoso vampiro. La novela de vampiros por excelencia.'],

            // ═══════════════════════════════════════════════════════════════
            // THRILLER Y MISTERIO
            // ═══════════════════════════════════════════════════════════════
            ['title'=>'El código Da Vinci','authors'=>['Dan Brown'],'genres'=>['Thriller','Misterio'],'price_cents'=>1199,'is_featured'=>true,'is_bestseller'=>true,'pages'=>489,'publisher'=>'Umbriel','description'=>'El simbólogo Robert Langdon investiga el asesinato del curador del Louvre y descubre una conspiración que involucra al Opus Dei y un secreto guardado por siglos sobre el Santo Grial. Thriller de acción trepidante.'],
            ['title'=>'La chica del tren','authors'=>['Paula Hawkins'],'genres'=>['Thriller'],'price_cents'=>1099,'is_bestseller'=>true,'pages'=>395,'publisher'=>'Planeta','description'=>'Rachel Watson observa a una pareja desde el tren todos los días hasta que la mujer desaparece. Un thriller psicológico narrado desde tres perspectivas femeninas con giros que no se pueden anticipar.'],
            ['title'=>'Perdida','authors'=>['Gillian Flynn'],'genres'=>['Thriller'],'price_cents'=>1199,'is_featured'=>true,'pages'=>432,'publisher'=>'Debolsillo','description'=>'En su quinto aniversario de boda, Amy Dunne desaparece. Las sospechas recaen sobre su marido Nick. Un thriller que examina el matrimonio, los medios de comunicación y las apariencias con un giro absolutamente devastador.'],
            ['title'=>'El silencio de los corderos','authors'=>['Thomas Harris'],'genres'=>['Thriller'],'price_cents'=>1199,'is_bestseller'=>true,'pages'=>367,'publisher'=>'Debolsillo','description'=>'La agente Clarice Starling debe obtener la ayuda del caníbal Hannibal Lecter para atrapar a un asesino en serie. Una novela que redefinió el género del thriller psicológico para siempre.'],
            ['title'=>'El nombre de la rosa','authors'=>['Umberto Eco'],'genres'=>['Thriller','Ficción Histórica'],'price_cents'=>1399,'is_featured'=>true,'pages'=>592,'publisher'=>'Lumen','description'=>'El monje franciscano Guillermo de Baskerville investiga muertes misteriosas en una abadía medieval. Un thriller intelectual que mezcla la semiótica, la filosofía medieval y el misterio policial con erudición asombrosa.'],
            ['title'=>'Asesinato en el Orient Express','authors'=>['Agatha Christie'],'genres'=>['Misterio'],'price_cents'=>999,'is_bestseller'=>true,'pages'=>256,'publisher'=>'Molino','description'=>'El detective Hercule Poirot queda varado en el Orient Express bloqueado por la nieve. Esa noche uno de los pasajeros es asesinado. Poirot debe resolver el misterio sin poder salir del tren. El mejor Agatha Christie.'],
            ['title'=>'Muerte en el Nilo','authors'=>['Agatha Christie'],'genres'=>['Misterio'],'price_cents'=>999,'pages'=>288,'publisher'=>'Molino','description'=>'En un crucero por el Nilo egipcio, la joven Linnet Doyle es asesinada. Hercule Poirot debe descubrir al asesino entre pasajeros, todos con motivos para el crimen. Christie en su mejor momento.'],
            ['title'=>'El perro de los Baskerville','authors'=>['Arthur Conan Doyle'],'genres'=>['Misterio'],'price_cents'=>799,'is_bestseller'=>true,'pages'=>224,'publisher'=>'Alianza','description'=>'Sherlock Holmes investiga la muerte de Sir Charles Baskerville, aparentemente aterrorizado por un perro fantasma que acosa a la familia según una leyenda del siglo XVII en los páramos de Dartmoor.'],
            ['title'=>'La sombra del viento','authors'=>['Carlos Ruiz Zafón'],'genres'=>['Misterio','Ficción'],'price_cents'=>1299,'is_featured'=>true,'is_bestseller'=>true,'pages'=>544,'publisher'=>'Planeta','description'=>'En la Barcelona de la posguerra, el joven Daniel encuentra una novela de Julián Carax en el Cementerio de los Libros Olvidados. Su búsqueda del misterioso autor le llevará a descubrir un oscuro y apasionante secreto.'],
            ['title'=>'El psicoanalista','authors'=>['John Katzenbach'],'genres'=>['Thriller'],'price_cents'=>1099,'pages'=>432,'publisher'=>'Ediciones B','description'=>'Un psicoanalista recibe una carta anónima: si no adivina quién es el remitente en un plazo determinado, uno de sus pacientes morirá cada día. Un thriller de gato y ratón de alta tensión psicológica.'],

            // ═══════════════════════════════════════════════════════════════
            // ROMANCE
            // ═══════════════════════════════════════════════════════════════
            ['title'=>'Orgullo y prejuicio','authors'=>['Jane Austen'],'genres'=>['Romance','Clásico'],'price_cents'=>899,'is_featured'=>true,'is_bestseller'=>true,'pages'=>432,'publisher'=>'Alianza','description'=>'Elizabeth Bennet y el aristocrático Mr. Darcy comienzan con antipatía mutua hasta que el amor supera sus prejuicios de clase. La novela de Jane Austen más amada, una joya de la literatura romántica inglesa.'],
            ['title'=>'Jane Eyre','authors'=>['Charlotte Brontë'],'genres'=>['Romance','Clásico'],'price_cents'=>999,'is_bestseller'=>true,'pages'=>560,'publisher'=>'Alba','description'=>'La huérfana Jane Eyre se enamora de su misterioso empleador, Rochester. Una historia de amor con elementos góticos y un poderoso mensaje feminista que sigue cautivando a lectores de todas las generaciones.'],
            ['title'=>'Cumbres borrascosas','authors'=>['Emily Brontë'],'genres'=>['Romance','Clásico'],'price_cents'=>899,'pages'=>384,'publisher'=>'Alba','description'=>'El apasionado y vengativo Heathcliff ama con obsesión a Catherine Earnshaw en los páramos de Yorkshire. Una historia de amor oscuro y venganza que trasciende generaciones. La novela romántica más oscura de la literatura inglesa.'],
            ['title'=>'Lo que el viento se llevó','authors'=>['Margaret Mitchell'],'genres'=>['Romance','Ficción Histórica'],'price_cents'=>1699,'is_bestseller'=>true,'pages'=>1037,'publisher'=>'Planeta','description'=>'Scarlett O\'Hara sobrevive a la Guerra Civil americana con tenacidad y astucia. Su amor por Ashley Wilkes y su compleja relación con Rhett Butler forman el corazón de esta épica historia inmortal.'],
            ['title'=>'Tokio Blues (Norwegian Wood)','authors'=>['Haruki Murakami'],'genres'=>['Romance','Ficción'],'price_cents'=>1199,'is_featured'=>true,'is_bestseller'=>true,'pages'=>336,'publisher'=>'Tusquets','description'=>'En el Tokio de finales de los 60, Watanabe recuerda su juventud y sus amores: la frágil Naoko y la vivaz Midori. Una novela sobre el duelo, la locura y el delicado proceso de crecer y amar.'],
            ['title'=>'Normal People','authors'=>['Sally Rooney'],'genres'=>['Romance','Ficción Contemporánea'],'price_cents'=>1099,'is_new_arrival'=>true,'pages'=>288,'publisher'=>'Anagrama','description'=>'Connell y Marianne se conocen en el instituto irlandés. Populares e inadaptados, inician una relación que los perseguirá hasta la universidad. Sobre el deseo, el poder y la clase social en el Irlanda contemporánea.'],

            // ═══════════════════════════════════════════════════════════════
            // AVENTURA
            // ═══════════════════════════════════════════════════════════════
            ['title'=>'El conde de Montecristo','authors'=>['Alexandre Dumas'],'genres'=>['Aventura','Clásico'],'price_cents'=>1599,'is_featured'=>true,'is_bestseller'=>true,'pages'=>1276,'publisher'=>'Alianza','description'=>'Edmond Dantès es falsamente encarcelado. Tras escapar, descubre un tesoro y regresa como el Conde de Montecristo para vengarse de quienes lo traicionaron. Una épica historia de venganza y justicia perfectamente construida.'],
            ['title'=>'Los tres mosqueteros','authors'=>['Alexandre Dumas'],'genres'=>['Aventura','Clásico'],'price_cents'=>1199,'is_bestseller'=>true,'pages'=>688,'publisher'=>'Alianza','description'=>'D\'Artagnan llega a París y se une a Athos, Porthos y Aramis para defender al rey de Francia. Acción, amistad y honor en la Francia del siglo XVII que no dejan descansar al lector.'],
            ['title'=>'Veinte mil leguas de viaje submarino','authors'=>['Julio Verne'],'genres'=>['Aventura','Ciencia Ficción'],'price_cents'=>999,'pages'=>368,'publisher'=>'Alianza','description'=>'El capitán Nemo navega los océanos en su submarino Nautilus. El profesor Aronnax es su involuntario huésped en un viaje que muestra las maravillas del mundo submarino y la grandeza de la naturaleza.'],
            ['title'=>'La vuelta al mundo en 80 días','authors'=>['Julio Verne'],'genres'=>['Aventura'],'price_cents'=>799,'pages'=>272,'publisher'=>'Alianza','description'=>'Phileas Fogg apuesta que puede dar la vuelta al mundo en 80 días. Con su criado Passepartout, vive aventuras en Asia, América y Europa en una carrera contra el tiempo llena de imprevistos.'],
            ['title'=>'La isla del tesoro','authors'=>['Robert Louis Stevenson'],'genres'=>['Aventura'],'price_cents'=>799,'pages'=>288,'publisher'=>'Alianza','description'=>'Jim Hawkins encuentra un mapa que lleva a una isla llena de tesoros piratas. Se embarca en una aventura llena de traiciones y encuentros con el memorable Long John Silver. El libro de aventuras por excelencia.'],

            // ═══════════════════════════════════════════════════════════════
            // FICCIÓN HISTÓRICA
            // ═══════════════════════════════════════════════════════════════
            ['title'=>'Los pilares de la tierra','authors'=>['Ken Follett'],'genres'=>['Ficción Histórica'],'price_cents'=>1599,'is_featured'=>true,'is_bestseller'=>true,'pages'=>973,'publisher'=>'Plaza & Janés','description'=>'La construcción de una catedral en la Inglaterra medieval del siglo XII. A través de décadas, distintos personajes se entrelazan en torno a este proyecto monumental mientras la guerra y la política sacuden el reino.'],
            ['title'=>'La catedral del mar','authors'=>['Ildefonso Falcones'],'genres'=>['Ficción Histórica'],'price_cents'=>1399,'is_bestseller'=>true,'pages'=>656,'publisher'=>'Grijalbo','description'=>'En la Barcelona del siglo XIV, el siervo Arnau Estanyol asciende socialmente mientras ayuda a construir la Basílica de Santa María del Mar. Una historia de amor, traición y redención en la Edad Media catalana.'],
            ['title'=>'Patria','authors'=>['Fernando Aramburu'],'genres'=>['Ficción','Ficción Histórica'],'price_cents'=>1499,'is_featured'=>true,'is_bestseller'=>true,'pages'=>656,'publisher'=>'Tusquets','description'=>'Dos familias amigas del País Vasco quedan enfrentadas durante décadas de terrorismo de ETA. Una novela polifónica sobre la violencia, la reconciliación y la memoria colectiva en España.'],
            ['title'=>'El maestro y Margarita','authors'=>['Mikhail Bulgákov'],'genres'=>['Ficción','Ficción Histórica'],'price_cents'=>1299,'is_featured'=>true,'pages'=>480,'publisher'=>'Alianza','description'=>'El diablo visita la Moscú soviética acompañado de un séquito alucinante. Mientras tanto, un escritor y su amante Margarita sufren por una novela sobre Poncio Pilatos. Una obra maestra de la literatura rusa.'],
            ['title'=>'La fiesta del Chivo','authors'=>['Mario Vargas Llosa'],'genres'=>['Ficción Histórica'],'price_cents'=>1299,'is_featured'=>true,'pages'=>528,'publisher'=>'Alfaguara','description'=>'Los últimos días de la dictadura de Trujillo en República Dominicana. Tres historias entrelazadas: el dictador, sus conspiradores y una mujer que regresa al país décadas después. Premio Planeta 2000.'],
            ['title'=>'Si esto es un hombre','authors'=>['Primo Levi'],'genres'=>['Biografía','Ficción Histórica'],'price_cents'=>1099,'is_featured'=>true,'pages'=>256,'publisher'=>'Muchnik','description'=>'El testimonio de Primo Levi sobre su supervivencia en Auschwitz. Una de las obras fundamentales sobre el Holocausto, narrada con precisión y serenidad que hace aún más devastador su contenido.'],

            // ═══════════════════════════════════════════════════════════════
            // FANTASÍA
            // ═══════════════════════════════════════════════════════════════
            ['title'=>'El señor de los anillos: La comunidad del anillo','authors'=>['J.R.R. Tolkien'],'genres'=>['Fantasía'],'price_cents'=>1499,'is_featured'=>true,'is_bestseller'=>true,'pages'=>544,'publisher'=>'Minotauro','description'=>'El hobbit Frodo Bolsón hereda un anillo mágico y debe destruirlo en Mordor. Se forma la Comunidad del Anillo para guiarlo. La obra fundacional de la fantasía épica moderna que inspiró todo el género.'],
            ['title'=>'El hobbit','authors'=>['J.R.R. Tolkien'],'genres'=>['Fantasía'],'price_cents'=>1199,'is_bestseller'=>true,'pages'=>310,'publisher'=>'Minotauro','description'=>'El tranquilo hobbit Bilbo Bolsón es reclutado por el mago Gandalf y trece enanos para recuperar el tesoro custodiado por el dragón Smaug. El preludio aventurero al universo de la Tierra Media.'],
            ['title'=>'Harry Potter y la piedra filosofal','authors'=>['J.K. Rowling'],'genres'=>['Fantasía'],'price_cents'=>1299,'is_bestseller'=>true,'pages'=>309,'publisher'=>'Salamandra','description'=>'Un niño descubre que es un mago y es enviado a Hogwarts. Allí hace amigos, aprende hechizos y descubre la verdad sobre sus padres y el poderoso Voldemort. El libro más vendido de los últimos 30 años.'],
            ['title'=>'La historia interminable','authors'=>['Michael Ende'],'genres'=>['Fantasía'],'price_cents'=>1099,'is_featured'=>true,'pages'=>462,'publisher'=>'Alfaguara','description'=>'Bastian encuentra un libro mágico que narra la historia de Fantasía, un mundo destruido por la Nada. Al leer, se convierte en parte de la historia y debe salvar ese mundo con su imaginación.'],
            ['title'=>'Coraline','authors'=>['Neil Gaiman'],'genres'=>['Fantasía','Terror'],'price_cents'=>899,'pages'=>176,'publisher'=>'Roca','description'=>'Coraline descubre una puerta secreta en su nueva casa que lleva a un mundo paralelo donde todo parece mejor. Pero ese mundo perfecto esconde un oscuro y peligroso secreto que amenaza su vida.'],
            ['title'=>'El nombre del viento','authors'=>['Patrick Rothfuss'],'genres'=>['Fantasía'],'price_cents'=>1399,'is_featured'=>true,'is_bestseller'=>true,'pages'=>662,'publisher'=>'Plaza & Janés','description'=>'Kvothe, considerado el mago más poderoso de su era, narra su propia historia desde su infancia entre nómadas hasta sus primeras hazañas legendarias. El inicio de la saga de fantasía más esperada del siglo XXI.'],

            // ═══════════════════════════════════════════════════════════════
            // AUTOAYUDA Y DESARROLLO PERSONAL
            // ═══════════════════════════════════════════════════════════════
            ['title'=>'El poder del ahora','authors'=>['Eckhart Tolle'],'genres'=>['Autoayuda'],'price_cents'=>1099,'is_featured'=>true,'is_bestseller'=>true,'pages'=>224,'publisher'=>'Gaia','description'=>'Tolle explica cómo liberarnos del sufrimiento mental viviendo plenamente en el momento presente. Un libro transformador que ha cambiado la vida de millones de lectores en todo el mundo.'],
            ['title'=>'Los siete hábitos de la gente altamente efectiva','authors'=>['Stephen R. Covey'],'genres'=>['Autoayuda'],'price_cents'=>1299,'is_bestseller'=>true,'pages'=>432,'publisher'=>'Paidós','description'=>'Covey presenta siete hábitos fundamentales para el desarrollo personal y profesional. Un clásico del liderazgo personal que sigue siendo relevante décadas después de su publicación.'],
            ['title'=>'El hombre en busca de sentido','authors'=>['Viktor Frankl'],'genres'=>['Autoayuda','Filosofía'],'price_cents'=>899,'is_featured'=>true,'is_bestseller'=>true,'pages'=>176,'publisher'=>'Herder','description'=>'El psiquiatra Viktor Frankl describe su supervivencia en los campos de concentración nazis y la logoterapia que desarrolló. Una obra profunda sobre encontrar significado incluso en el mayor sufrimiento.'],
            ['title'=>'Hábitos atómicos','authors'=>['James Clear'],'genres'=>['Autoayuda'],'price_cents'=>1199,'is_featured'=>true,'is_bestseller'=>true,'is_new_arrival'=>true,'pages'=>320,'publisher'=>'Diana','description'=>'James Clear explica cómo pequeños cambios de comportamiento pueden conducir a resultados notables. El sistema de los cuatro pasos para construir buenos hábitos y eliminar los malos. El libro de autoayuda más vendido actualmente.'],
            ['title'=>'Cómo ganar amigos e influir sobre las personas','authors'=>['Dale Carnegie'],'genres'=>['Autoayuda'],'price_cents'=>999,'is_bestseller'=>true,'pages'=>320,'publisher'=>'Elipse','description'=>'Publicado en 1936, este libro sigue siendo un referente de las habilidades sociales. Carnegie enseña principios atemporales para relacionarse mejor con los demás y liderar con empatía y comprensión.'],
            ['title'=>'Mindset: La actitud del éxito','authors'=>['Carol S. Dweck'],'genres'=>['Autoayuda'],'price_cents'=>1099,'is_new_arrival'=>true,'pages'=>288,'publisher'=>'Sirio','description'=>'La psicóloga Carol Dweck distingue entre mentalidad fija y mentalidad de crecimiento. Las personas con mentalidad de crecimiento creen que sus habilidades pueden desarrollarse y logran más en todos los ámbitos.'],
            ['title'=>'Piense y hágase rico','authors'=>['Napoleon Hill'],'genres'=>['Autoayuda'],'price_cents'=>999,'is_bestseller'=>true,'pages'=>320,'publisher'=>'Ediciones Obelisco','description'=>'Basado en entrevistas con los hombres más exitosos de América, Hill destila los principios del éxito financiero y personal. Un clásico de la mentalidad emprendedora que ha inspirado generaciones de líderes.'],
            ['title'=>'El arte de no amargarse la vida','authors'=>['Rafael Santandreu'],'genres'=>['Autoayuda'],'price_cents'=>1099,'is_bestseller'=>true,'pages'=>256,'publisher'=>'Grijalbo','description'=>'El psicólogo Rafael Santandreu explica cómo la psicología cognitiva puede cambiar nuestra forma de ver el mundo y vivir con más plenitud y bienestar personal. Un libro práctico y transformador.'],

            // ═══════════════════════════════════════════════════════════════
            // FILOSOFÍA
            // ═══════════════════════════════════════════════════════════════
            ['title'=>'El extranjero','authors'=>['Albert Camus'],'genres'=>['Filosofía','Ficción'],'price_cents'=>899,'is_featured'=>true,'is_bestseller'=>true,'pages'=>160,'publisher'=>'Alianza','description'=>'Meursault, un hombre emocionalmente distante, mata a un árabe en una playa y es juzgado más por su indiferencia que por el crimen. La novela del absurdo por excelencia, esencial para entender el existencialismo.'],
            ['title'=>'La peste','authors'=>['Albert Camus'],'genres'=>['Filosofía','Ficción'],'price_cents'=>999,'is_bestseller'=>true,'pages'=>320,'publisher'=>'Alianza','description'=>'Una epidemia de peste azota la ciudad argelina de Orán. El doctor Rieux y otros personajes responden al desastre de formas diferentes. Camus usa la epidemia como metáfora del fascismo y la condición humana.'],
            ['title'=>'Meditaciones','authors'=>['Marco Aurelio'],'genres'=>['Filosofía'],'price_cents'=>899,'is_featured'=>true,'pages'=>256,'publisher'=>'Alianza','description'=>'El diario personal del emperador romano Marco Aurelio recoge sus reflexiones estoicas sobre la virtud, la muerte, el tiempo y el deber. Una de las obras más atesoradas del estoicismo y la filosofía antigua.'],
            ['title'=>'Así habló Zaratustra','authors'=>['Friedrich Nietzsche'],'genres'=>['Filosofía'],'price_cents'=>1099,'pages'=>384,'publisher'=>'Alianza','description'=>'Zaratustra desciende de su montaña para enseñar al hombre la idea del superhombre, la voluntad de poder y el eterno retorno. La obra más poética y accesible de Nietzsche, escrita en forma de parábolas.'],
            ['title'=>'Siddhartha','authors'=>['Hermann Hesse'],'genres'=>['Filosofía','Ficción'],'price_cents'=>799,'is_featured'=>true,'pages'=>152,'publisher'=>'Alianza','description'=>'El joven indio Siddhartha abandona los privilegios para buscar la iluminación. Una novela breve y profunda sobre el camino espiritual que ha guiado a millones de lectores hacia la serenidad interior.'],
            ['title'=>'El lobo estepario','authors'=>['Hermann Hesse'],'genres'=>['Filosofía','Ficción'],'price_cents'=>1099,'pages'=>280,'publisher'=>'Alianza','description'=>'Harry Haller, un hombre que se siente mitad humano y mitad lobo salvaje, encuentra en una ciudad alemana el Teatro Mágico donde todo es posible. Una exploración de la doble naturaleza humana.'],
            ['title'=>'Narciso y Goldmundo','authors'=>['Hermann Hesse'],'genres'=>['Ficción','Filosófico'],'price_cents'=>1099,'pages'=>304,'publisher'=>'Alianza','description'=>'Dos amigos en la Edad Media siguen caminos opuestos: Narciso elige la vida contemplativa del monje, Goldmundo abandona el monasterio para vivir la vida sensual del artista. Una meditación sobre el espíritu y la carne.'],

            // ═══════════════════════════════════════════════════════════════
            // CIENCIAS Y DIVULGACIÓN
            // ═══════════════════════════════════════════════════════════════
            ['title'=>'Una breve historia del tiempo','authors'=>['Stephen Hawking'],'genres'=>['Ciencias','Divulgación'],'price_cents'=>1199,'is_featured'=>true,'is_bestseller'=>true,'pages'=>240,'publisher'=>'Crítica','description'=>'Hawking explica los conceptos más complejos de la física moderna para el público general: el Big Bang, los agujeros negros y la teoría del todo. Uno de los libros de ciencia más vendidos de la historia.'],
            ['title'=>'Cosmos','authors'=>['Carl Sagan'],'genres'=>['Ciencias','Divulgación'],'price_cents'=>1299,'is_bestseller'=>true,'pages'=>368,'publisher'=>'Planeta','description'=>'Carl Sagan recorre la historia del universo, de la ciencia y de la humanidad. Un viaje apasionante por la astronomía que captura la maravilla del cosmos de manera accesible para cualquier lector.'],
            ['title'=>'Sapiens: De animales a dioses','authors'=>['Yuval Noah Harari'],'genres'=>['Ciencias','Historia','Divulgación'],'price_cents'=>1399,'is_featured'=>true,'is_bestseller'=>true,'pages'=>496,'publisher'=>'Debate','description'=>'Harari recorre la historia de la humanidad desde el Homo sapiens primitivo. Explora cómo la capacidad de crear ficciones colectivas como el dinero, las naciones y las religiones permitió dominar el planeta.'],
            ['title'=>'Homo Deus','authors'=>['Yuval Noah Harari'],'genres'=>['Ciencias','Divulgación'],'price_cents'=>1399,'is_new_arrival'=>true,'pages'=>464,'publisher'=>'Debate','description'=>'Explora el futuro de la humanidad. A medida que logramos controlar el hambre y las enfermedades, ¿cuáles serán los próximos proyectos de la humanidad? ¿Buscaremos la inmortalidad y la felicidad perpetua?'],
            ['title'=>'El gen egoísta','authors'=>['Richard Dawkins'],'genres'=>['Ciencias'],'price_cents'=>1199,'pages'=>360,'publisher'=>'Salvat','description'=>'Dawkins presenta la evolución desde la perspectiva del gen, argumentando que los organismos son máquinas de supervivencia creadas por los genes para perpetuarse. Introdujo el concepto de meme al mundo.'],
            ['title'=>'El origen de las especies','authors'=>['Charles Darwin'],'genres'=>['Ciencias'],'price_cents'=>999,'pages'=>528,'publisher'=>'Alianza','description'=>'Darwin presenta la teoría de la evolución por selección natural. Un libro que cambió para siempre nuestra comprensión del origen de la vida y del lugar de los seres humanos en la naturaleza.'],

            // ═══════════════════════════════════════════════════════════════
            // BIOGRAFÍAS Y MEMORIAS
            // ═══════════════════════════════════════════════════════════════
            ['title'=>'El diario de Ana Frank','authors'=>['Ana Frank'],'genres'=>['Biografía'],'price_cents'=>899,'is_featured'=>true,'is_bestseller'=>true,'pages'=>304,'publisher'=>'Plaza & Janés','description'=>'Los diarios de una niña judía que se escondió de los nazis en Ámsterdam durante más de dos años. Un testimonio conmovedor de la Segunda Guerra Mundial y del Holocausto que no deja indiferente a nadie.'],
            ['title'=>'Steve Jobs','authors'=>['Walter Isaacson'],'genres'=>['Biografía'],'price_cents'=>1499,'is_bestseller'=>true,'pages'=>656,'publisher'=>'Debate','description'=>'La biografía autorizada del cofundador de Apple. Isaacson retrata a Jobs como un genio visionario pero también como un hombre difícil, a través de cientos de entrevistas con él mismo y sus colaboradores.'],
            ['title'=>'El largo camino hacia la libertad','authors'=>['Nelson Mandela'],'genres'=>['Biografía'],'price_cents'=>1399,'is_featured'=>true,'pages'=>656,'publisher'=>'Aguilar','description'=>'La autobiografía de Nelson Mandela, desde su infancia hasta su presidencia en Sudáfrica. Un testimonio extraordinario sobre la lucha contra el apartheid y la búsqueda de la reconciliación nacional.'],
            ['title'=>'En el camino','authors'=>['Jack Kerouac'],'genres'=>['Biografía','Ficción'],'price_cents'=>1099,'pages'=>408,'publisher'=>'Anagrama','description'=>'Sal Paradise y Dean Moriarty recorren los Estados Unidos capturando el espíritu de la generación Beat. Una novela autobiográfica que celebra la libertad, el jazz y la búsqueda de la autenticidad vital.'],

            // ═══════════════════════════════════════════════════════════════
            // POESÍA
            // ═══════════════════════════════════════════════════════════════
            ['title'=>'Veinte poemas de amor y una canción desesperada','authors'=>['Pablo Neruda'],'genres'=>['Poesía'],'price_cents'=>699,'is_featured'=>true,'is_bestseller'=>true,'pages'=>96,'publisher'=>'Seix Barral','description'=>'La primera gran obra de Neruda, escrita a los 19 años. Veinte poemas que exploran con pasión y melancolía el amor joven, el deseo y el abandono. El poemario más vendido en lengua española de todos los tiempos.'],
            ['title'=>'Canto general','authors'=>['Pablo Neruda'],'genres'=>['Poesía'],'price_cents'=>999,'pages'=>608,'publisher'=>'Seix Barral','description'=>'La obra épica de Neruda que recorre la historia de América Latina desde la naturaleza precolombina hasta las luchas políticas del siglo XX. Un monumento poético de 340 poemas que celebra el continente.'],
            ['title'=>'Residencia en la tierra','authors'=>['Pablo Neruda'],'genres'=>['Poesía'],'price_cents'=>899,'pages'=>280,'publisher'=>'Seix Barral','description'=>'Los poemas más herméticos y surrealistas de Neruda, escritos durante su estadía en Asia. Una exploración oscura del desamparo, la decadencia y la dificultad de comunicarse. El Neruda vanguardista en estado puro.'],

            // ═══════════════════════════════════════════════════════════════
            // FICCIÓN CONTEMPORÁNEA ADICIONAL
            // ═══════════════════════════════════════════════════════════════
            ['title'=>'El alquimista','authors'=>['Paulo Coelho'],'genres'=>['Ficción','Filosófico'],'price_cents'=>999,'is_featured'=>true,'is_bestseller'=>true,'pages'=>208,'publisher'=>'Planeta','description'=>'El pastor andaluz Santiago sigue los sueños que le indican un tesoro junto a las pirámides. Un viaje iniciático sobre escuchar el corazón y seguir los sueños. El libro más traducido de un autor vivo en la historia.'],
            ['title'=>'La conjura de los necios','authors'=>['John Kennedy Toole'],'genres'=>['Ficción Contemporánea'],'price_cents'=>1199,'is_featured'=>true,'pages'=>432,'publisher'=>'Anagrama','description'=>'Ignatius J. Reilly, un excéntrico intelectual en el Nueva Orleans de los años 60, protagoniza desventuras cómicas y filosóficas. Premio Pulitzer póstumo. Una novela de humor corrosivo e irresistible.'],
            ['title'=>'El guardián entre el centeno','authors'=>['J.D. Salinger'],'genres'=>['Ficción'],'price_cents'=>999,'is_bestseller'=>true,'pages'=>280,'publisher'=>'Alianza','description'=>'Holden Caulfield, expulsado de su internado, vaga por Nueva York durante dos días. Su monólogo interno captura la alienación adolescente con una voz que sigue siendo fresca e irresistible décadas después.'],
            ['title'=>'Kafka en la orilla','authors'=>['Haruki Murakami'],'genres'=>['Ficción Contemporánea'],'price_cents'=>1299,'is_featured'=>true,'pages'=>600,'publisher'=>'Tusquets','description'=>'Dos historias paralelas: un joven de 15 años que huye de su padre y un anciano que perdió la memoria. Sus caminos se entrecruzan en un universo donde lo real y lo fantástico se fusionan magistralmente.'],
            ['title'=>'Todo se desmorona','authors'=>['Chinua Achebe'],'genres'=>['Ficción','Ficción Histórica'],'price_cents'=>999,'is_featured'=>true,'pages'=>208,'publisher'=>'Alfaguara','description'=>'Okonkwo, un líder igbo en Nigeria, ve cómo la llegada de los colonizadores europeos destruye el tejido social de su pueblo. Una novela fundacional de la literatura africana en inglés que cambió la narrativa global.'],
            ['title'=>'El dios de las pequeñas cosas','authors'=>['Arundhati Roy'],'genres'=>['Ficción Contemporánea'],'price_cents'=>1099,'is_featured'=>true,'pages'=>368,'publisher'=>'Anagrama','description'=>'En Kerala, India, los gemelos Rahel y Estha viven la tragedia que marcará sus vidas. Una novela sobre las castas, el amor prohibido y la injusticia social narrada con una prosa de extraordinaria belleza.'],
            ['title'=>'Stoner','authors'=>['John Williams'],'genres'=>['Ficción Contemporánea'],'price_cents'=>1099,'is_featured'=>true,'pages'=>304,'publisher'=>'Baile del Sol','description'=>'William Stoner, hijo de granjeros que se convierte en profesor universitario, vive una vida aparentemente pequeña. Una novela sobre la dignidad silenciosa, el amor a la literatura y la belleza de las vidas ordinarias.'],
            ['title'=>'Beloved','authors'=>['Toni Morrison'],'genres'=>['Ficción'],'price_cents'=>1199,'is_featured'=>true,'pages'=>336,'publisher'=>'Ediciones B','description'=>'Una exesclava en Ohio es atormentada por el fantasma de la hija que mató para liberarla de la esclavitud. Premio Nobel de Literatura. Una obra sobre trauma, memoria y el legado de la esclavitud americana.'],
            ['title'=>'Los detectives salvajes','authors'=>['Roberto Bolaño'],'genres'=>['Ficción'],'price_cents'=>1399,'is_featured'=>true,'pages'=>609,'publisher'=>'Anagrama','description'=>'Arturo Belano y Ulises Lima buscan a la misteriosa poeta Cesárea Tinajero. Una novela polifónica que retrata a una generación de poetas latinoamericanos entre México, Europa y África con energía arrolladora.'],
            ['title'=>'2666','authors'=>['Roberto Bolaño'],'genres'=>['Ficción'],'price_cents'=>1799,'is_featured'=>true,'pages'=>1119,'publisher'=>'Anagrama','description'=>'Una obra monumental dividida en cinco partes que convergen en la ciudad fronteriza de Santa Teresa, donde cientos de mujeres son asesinadas. La obra magna póstuma de Bolaño, una de las mejores novelas del siglo XXI.'],
            ['title'=>'El perfume','authors'=>['Patrick Süskind'],'genres'=>['Ficción'],'price_cents'=>1099,'is_bestseller'=>true,'pages'=>320,'publisher'=>'Seix Barral','description'=>'Jean-Baptiste Grenouille nace en la Francia del siglo XVIII con un extraordinario sentido del olfato pero sin olor propio. Obsesionado con capturar el perfume perfecto, comete crímenes atroces e imperdonables.'],
            ['title'=>'Zorba el griego','authors'=>['Nikos Kazantzakis'],'genres'=>['Ficción'],'price_cents'=>1099,'is_featured'=>true,'pages'=>368,'publisher'=>'Planeta','description'=>'Un intelectual griego conoce a Zorba, un hombre lleno de vitalidad que abraza la vida con intensidad desbordante. Una novela sobre la tensión entre el pensamiento y la acción, el espíritu y la materia.'],
            ['title'=>'Las uvas de la ira','authors'=>['John Steinbeck'],'genres'=>['Clásico','Ficción'],'price_cents'=>1199,'is_featured'=>true,'pages'=>544,'publisher'=>'Alianza','description'=>'La familia Joad emigra de Oklahoma a California durante la Gran Depresión buscando trabajo. Una novela épica sobre la explotación de trabajadores migrantes y la solidaridad humana. Premio Pulitzer 1940.'],
            ['title'=>'Pantaleón y las visitadoras','authors'=>['Mario Vargas Llosa'],'genres'=>['Ficción'],'price_cents'=>1099,'pages'=>288,'publisher'=>'Seix Barral','description'=>'El capitán Pantaleón Pantoja recibe la misión secreta de organizar un servicio de prostitutas para los soldados de la Amazonía peruana. Una novela satírica y erótica sobre la burocracia militar y la sexualidad.'],
            ['title'=>'El jardín de los Finzi-Contini','authors'=>['Giorgio Bassani'],'genres'=>['Ficción Histórica'],'price_cents'=>1099,'pages'=>280,'publisher'=>'Alianza','description'=>'En la Ferrara de los años 30, el narrador está enamorado de Micol Finzi-Contini, hija de una familia judía aristócrata. Mientras el fascismo avanza, el jardín de los Finzi-Contini es el último refugio.'],
            ['title'=>'El jugador','authors'=>['Fiodor Dostoievski'],'genres'=>['Clásico'],'price_cents'=>799,'pages'=>192,'publisher'=>'Alianza','description'=>'Un joven tutore ruso narra su adicción al juego y su amor imposible por Polina. Dostoievski escribió esta novela en 26 días para pagar sus propias deudas de juego. Un retrato devastador de la adicción.'],
        ];
    }
}
